/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alojamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accommodations with pagination
         * @description Get a paginated list of Portuguese accommodations
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default: 1) */
                    page?: number;
                    /** @description Items per page (default: 20, max: 100) */
                    limit?: number;
                    /** @description Sort field (id, nr_rnal, denominacao, concelho, distrito, created_at) */
                    sort?: string;
                    /** @description Sort order (asc, desc) */
                    order?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.PaginatedResponse-models_AlojamentoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alojamentos/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search accommodations with filters
         * @description Search accommodations with various filters and pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default: 1) */
                    page?: number;
                    /** @description Items per page (default: 20, max: 100) */
                    limit?: number;
                    /** @description Sort field (id, nr_rnal, denominacao, concelho, distrito, created_at) */
                    sort?: string;
                    /** @description Sort order (asc, desc) */
                    order?: string;
                    /** @description Filter by municipality */
                    concelho?: string;
                    /** @description Filter by district */
                    distrito?: string;
                    /** @description Filter by accommodation type */
                    modalidade?: string;
                    /** @description Filter by owner email */
                    email?: string;
                    /** @description Minimum capacity */
                    min_capacity?: number;
                    /** @description Maximum capacity */
                    max_capacity?: number;
                    /** @description Minimum latitude */
                    min_lat?: number;
                    /** @description Maximum latitude */
                    max_lat?: number;
                    /** @description Minimum longitude */
                    min_lng?: number;
                    /** @description Maximum longitude */
                    max_lng?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.PaginatedResponse-models_AlojamentoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alojamentos/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get accommodation statistics
         * @description Get aggregated statistics about accommodations
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.StatsResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alojamentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get accommodation by ID
         * @description Get a single accommodation by its ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Accommodation ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.AlojamentoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "models.AlojamentoResponse": {
            codigo_postal?: string;
            concelho?: string;
            created_at?: string;
            data_abertura_publico?: string;
            data_registo?: string;
            denominacao?: string;
            distrito?: string;
            email?: string;
            endereco?: string;
            freguesia?: string;
            id?: number;
            latitude?: number;
            localidade?: string;
            longitude?: number;
            modalidade?: string;
            nr_rnal?: number;
            nr_utentes?: number;
        };
        "models.DistrictStats": {
            count?: number;
            distrito?: string;
        };
        "models.ErrorResponse": {
            details?: {
                [key: string]: string;
            };
            error?: string;
        };
        "models.MunicipalityStats": {
            concelho?: string;
            count?: number;
        };
        "models.PaginatedResponse-models_AlojamentoResponse": {
            data?: components["schemas"]["models.AlojamentoResponse"][];
            pagination?: components["schemas"]["models.PaginationMeta"];
        };
        "models.PaginationMeta": {
            has_more?: boolean;
            limit?: number;
            page?: number;
            total?: number;
        };
        "models.StatsResponse": {
            average_capacity?: number;
            by_concelho?: components["schemas"]["models.MunicipalityStats"][];
            by_distrito?: components["schemas"]["models.DistrictStats"][];
            by_modalidade?: components["schemas"]["models.TypeStats"][];
            total_accommodations?: number;
        };
        "models.TypeStats": {
            count?: number;
            modalidade?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
